### ISSUE TITLE
Latest Hyperlink breaks Twisted on Python 3's test suite

### ISSUE THREAD

**Issue by hawkowl** [python-hyper/hyperlink#10]
```
[FAIL]
Traceback (most recent call last):
  File "/buildslave/fedora25-py3.5-coverage/Twisted/build/py35-alldeps-withcov-posix/lib/python3.5/site-packages/twisted/python/test/test_url.py", line 750, in test_invalidArguments
    check("scheme")
  File "/buildslave/fedora25-py3.5-coverage/Twisted/build/py35-alldeps-withcov-posix/lib/python3.5/site-packages/twisted/python/test/test_url.py", line 749, in check
    assertRaised(raised, expectation, param)
  File "/buildslave/fedora25-py3.5-coverage/Twisted/build/py35-alldeps-withcov-posix/lib/python3.5/site-packages/twisted/python/test/test_url.py", line 744, in assertRaised
    name, "<unexpected>"))
  File "/buildslave/fedora25-py3.5-coverage/Twisted/build/py35-alldeps-withcov-posix/lib/python3.5/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.5/unittest/case.py", line 1210, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: 'expected unicode for scheme, got <unexpected>' != 'expected str for scheme, got <unexpected>'
- expected unicode for scheme, got <unexpected>
?          ^^^^^^^
+ expected str for scheme, got <unexpected>
?          ^^^


twisted.python.test.test_url.TestURL.test_invalidArguments
```

Related to https://github.com/python-hyper/hyperlink/commit/d26814c074c6f9787e62af907df17fbd68fde615 changing the exception handling

cc @mahmoud

**Comment by mahmoud** [comment]
Ah, ok! I'll get this sorted shortly!

**Comment by hawkowl** [comment]
@mahmoud thanks!
