### ISSUE TITLE
Example does not work with python 2.7

### ISSUE THREAD

**Issue by kyrios123** [python-hyper/hyperlink#51]
I am trying to execute the example given in the [README.md](https://github.com/python-hyper/hyperlink/blob/master/README.md#installation). With python 3.5 it works just fine, with python 2.7 it fails with the following error. Did I miss something ?
```
Python 2.7.13 (default, Jan 12 2017, 13:55:14) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from hyperlink import URL
>>> url = URL.from_text('http://github.com/mahmoud/hyperlink?utm_source=README')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hyperlink/_url.py", line 971, in from_text
    um = _URL_RE.match(_textcheck('text', text))
  File "/usr/lib/python2.7/site-packages/hyperlink/_url.py", line 430, in _textcheck
    raise TypeError('expected %s for %s, got %r' % (exp, name, value))
TypeError: expected unicode for text, got 'http://github.com/mahmoud/hyperlink?utm_source=README'
>>> 

```

**Comment by mahmoud** [comment]
Hey @kyrios123! Yes, that URL string simply needs to be  `u'http://github.com/mahmoud/hyperlink?utm_source=README'`. I've just pushed a change to fix it. Thanks for the report!
